### ISSUE TITLE
[Bug]: Can't unlock abilities on chocobo

### ISSUE THREAD

**Issue by leafreynolds** [Mrbysco/ChocoCraft4#10]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

36.2.27

### Mod version

chococraft-1.16.5-0.2.1

### Java version

1.8.0_51

### Issue Description

Hi there! I'm struggling to get chocobos to unlock their abilities. I've tried using the ability fruit and chocopedia, making sure I have enough xp in both cases.. 
There's nothing in the latest.log or the debug.log.

![javaw_aBWYNyK3zz](https://user-images.githubusercontent.com/80794784/156693496-db223552-f4e3-4459-b90d-aa85f68b8cec.png)

**Comment by Didacus12** [comment]
I have same problem with chococraft-1.18.1-0.2.2. Forge 1.18.1 server, with modpack  single-player or multi-player.

**Comment by son0fether** [comment]
@najlitarvan There's no version of this Chococraft mod for 1.18.1 listed here: https://www.curseforge.com/minecraft/mc-mods/chococraft/files  How are you using it for 1.18.1?

**Comment by Mrbysco** [comment]
> @najlitarvan There's no version of this Chococraft mod for 1.18.1 listed here: https://www.curseforge.com/minecraft/mc-mods/chococraft/files How are you using it for 1.18.1?

There is actually a 1.18.1 version but it's marked alpha so it won't show up in the curseforge launcher

**Comment by son0fether** [comment]
I and all of my friends are also experiencing this on 1.16.5.  Chocobos of special colors from breeding also don't have the abilities (lots of work wasted).  Chocobos of special colors from spawn eggs also don't have the special abilities.

I don't think there's any problem with the abilities themselves, only the gaining of abilities.  I have used a command to grant the various abilities successfully, and then the abilities work with the bird.  Something like:
/data entity merge @e[sort=nearest,limit=1,type=chococraft:chocobo...(use auto-complete for type)] {CanSprint:1b,CanGlide:1b,CanFly:1b}

**Comment by Mrbysco** [comment]
The ability system has been abandoned in 1.18.2+
