### ISSUE TITLE
[Bug]: Chocopedia Not working

### ISSUE THREAD

**Issue by Tactfuljoint** [Mrbysco/ChocoCraft4#15]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [x] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.1.25

### Mod version

chococraft-1.18.2-0.4.3.jar

### Java version

Java 17

### Issue Description

Hello,

 I'm encountering a bug within the mod where the chocopedia firstly displays texts not on the book (Rather off to the side of the screen), containing the start 7 pages. However, when I go to use the book on the chocobo to change name, have them sit,, etc. nothing occurs. I have tested in both my normal world as well as a creative world on the array of chocobo types, using all manner items within the mod but with no degree of success. I have a number of mods aside from this one, and have not had any crashes, but due to the inability to have them sit/stay, they continue to become trapped in doorways which causes them to die. Please let me know if this is an issue on my end of if it is a bug.

Thank you

### Additional Information

![2022-08-09_05 38 57](https://user-images.githubusercontent.com/110898163/183617306-2dbfc848-cd05-45f7-8a8f-388ec1c20a04.png)

**Comment by DePhoegon** [comment]
> The entire ability system that was originally added in Chococraft 3 has been removed recently including the ability to rename chocobo's using the book.
> 
> I'll see what I can do about the text rendering outside the bounds of the book.
> 
> You can make a chocobo stay by using the whistle

That's literally  including the half width & half hieght to the draw of the text position.  (solved it myself before cutting the book out)

**Comment by Mrbysco** [comment]
It's also as easy as just using name-tags for their intended purpose

**Comment by Mrbysco** [comment]
Whoops, didn't mean to close it as the chocopedia render bug isn't fixed yet but will be next version

**Comment by Tactfuljoint** [comment]
> It's also as easy as just using name-tags for their intended purpose

Thanks for all the info, the mod page on Curseforge does not make mention of the whistle but it definitely works. However, the name tag does not. I have named the nametag as a random name (Jinx) and the original name of the chocobo is "Ice". When attempting to use the name tag nothing occurs. I tried screenshotting to show, but its not that great a screenshot. If the renaming is not possible please let me know. (I would like to If I can). 

![2022-08-09_14 35 28](https://user-images.githubusercontent.com/110898163/183736225-7ec5e934-3897-4a6f-940f-5f0b9a3b56c0.png)

**Comment by Mrbysco** [comment]
🤔  I'll look into it and make sure name-tags work again

**Comment by Mrbysco** [comment]
I've uploaded new 1.18 and 1.19 versions that fix the chocopedia and also fix nametags not working

**Comment by Tactfuljoint** [comment]
You are awesome, and thank you for such quick responses to my questions. Much appreciated.
