### ISSUE TITLE
[Suggestion]: Supplying My Chocoo Inventory Fix

### ISSUE THREAD

**Issue by DePhoegon** [Mrbysco/ChocoCraft4#16]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

How exactly would I go about helping fix this.  (I just solved it in my port/fork)  for 1.18.2) and would like to atleast give something back & add quick itemstack movement to the chocobo inventory.

I worked the bugs out & is stable, working as intended.

**Comment by Mrbysco** [comment]
I've already fixed the chocobo inventory in my 1.18.2 version

**Comment by DePhoegon** [comment]
Glad to know. X}  wasn't sure either way, just saw the inventory one.  but at any rate. Wish you luck with it X}   

Just saw the ticket and thought I'd offer it.    If there is anything I can help with, I'll be glad to.,  mostly X}  Just a bit willing to help.
