### ISSUE TITLE
[Bug]: Can't use golden gysahl at all

### ISSUE THREAD

**Issue by nekhs** [Mrbysco/ChocoCraft4#17]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

40.1.54

### Mod version

1.18.2.0.4.2

### Java version

idk one of them

### Issue Description

Can't breed black and white chocobos with golden gysahls. According to another user, you also cannot breed golden chocobos with golden gysahl. 

Tested rather thoroughly in survival multiplayer, did not see issue resolved in changelogs.

Can't seem to breed black and white chocobos to get golden chocobos without using golden gysahl either.

**Comment by Mrbysco** [comment]
Fixed in 0.4.6 (also backported to 1.16.5 in 0.3.2)
New jars have been uploaded and will be available shortly
