### ISSUE TITLE
[Bug]: Golden Gysahl on Golden Chocobo Yields Yellow Baby

### ISSUE THREAD

**Issue by nekhs** [Mrbysco/ChocoCraft4#18]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

current

### Mod version

current

### Java version

current?

### Issue Description

Book says golden gysahl on golden chocobo should always yield golden babies. Instead it seems to primarily if not always yield yellow babies. 

Can obtain golden babies from black/white chocobo pairings, however.

**Comment by Mrbysco** [comment]
Current means absolutely nothing.
I'll look into the breeding but please in the future actually fill out the form correctly
