### ISSUE TITLE
[Bug]: Chocobos keep teleporting to me, even in ''Wander'' mode

### ISSUE THREAD

**Issue by Joki2904** [Mrbysco/ChocoCraft4#19]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

41.1.0

### Mod version

0.4.7

### Java version

Java 8

### Issue Description

I can't make my domesticated chocobos stop following me, even if I set them to ''Wander'' mode with a whistle. 
They just keep teleporting near me, like wolves do. 
''Stay'' mode does work, but with that they just remain static, without making noises, and I rather let them move freely.

Any help? Thanks beforehand! 

### Additional Information

My Minecraft version is 1.19 if that helps. I have tried the previous mod versions and it still happens for some reason.

**Comment by DMasterIO** [comment]
Hi, this bug is also present in version forge 1.18.2

**Comment by Mrbysco** [comment]
New version will be up shortly
