### ISSUE TITLE
Dismounting a chocobo on a server causes client/server sync issues.

### ISSUE THREAD

**Issue by darkphan** [Mrbysco/ChocoCraft4#2]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

36.2.8

### Mod version

0.1.1

### Java version

java 8 update 282

### Issue Description

When dismounting a chocobo on a server there is a client/server sync issue. Sometimes resulting in the chocobo moving when you move, or chocobo "floating" above the ground, etc.

**Comment by Trawne** [comment]
I have also ran into this a few times. Logging out of the server will cause both you and the chocobo to vanish. Logging back in will log you in still mounted.

It only happens occasionally and I have to be moving when dismounting to trigger it. Standing still and dismounting I have yet to see this happen.

Other info-
MC: 1.16.5
Forge: 36.3.8
Chococraft: 0.2.1

**Comment by son0fether** [comment]
I am have also experienced this.  Client acted as though I was sort of still on chocobo, but I moved at a different speed as the chocobo, so it ended up moving sort of parallel to me.  Logging out and back in fixed it, and the chocobo was where I got off of it.  I may or may not have been in motion while dismounting.

MC: 1.16.5
Forge: 36.2.28
Chococraft: 0.2.1

**Comment by Mrbysco** [comment]
I've uploaded a new jar which overhauls the chocobo system, I'm going to close the issue but if the issue persist please comment
