### ISSUE TITLE
[Bug]: Chocobos Flying or Swimming is Crazy fast!

### ISSUE THREAD

**Issue by EchJetzt445** [Mrbysco/ChocoCraft4#20]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

41.1.0

### Mod version

0.4.8

### Java version

Java 17

### Issue Description

The Cocobos are Flying and Swimming to fast for the Server to render.

**Comment by Joki2904** [comment]
I do agree with this! It can be helpful sometimes, but it does indeed look a bit ''broken'' and too OP

**Comment by Mrbysco** [comment]
I've uploaded a new version that should fix them zooming all over the place
