### ISSUE TITLE
[Bug]: I want to put skills on the chocobo but the chocopedia doesn't work

### ISSUE THREAD

**Issue by dani12344444** [Mrbysco/ChocoCraft4#21]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

42.0.9

### Mod version

0.4.8

### Java version

Java 8 update 331

### Issue Description

I want to put skills on the chocobo but the chocopedia doesn't work

**Comment by dani12344444** [comment]
I want to put skills on the chocobo but the chocopedia doesn't work

**Comment by Mrbysco** [comment]
The ability system has been removed

**Comment by dani12344444** [comment]
So you can't fly or dive or anything like that?

**Comment by Mrbysco** [comment]
The abilities are tied to the color of the chocobo's just like in the older versions of the mod

**Comment by dani12344444** [comment]
where do I see what each color does?

**Comment by Mrbysco** [comment]
If you have the Patchouli mod installed the Chocopedia will have a bunch more info, including info about each color and their abilities
