### ISSUE TITLE
[Bug]: Flame Chocobos do not spawn in the Nether

### ISSUE THREAD

**Issue by Joki2904** [Mrbysco/ChocoCraft4#22]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

41.1.0

### Mod version

0.4.8

### Java version

Java 8

### Issue Description

After flying through the Nether I ended up noticing that not a single Flame Chocobo seems to be spawning, even after I used the command /tp @e. It seems there is an issue with their spawn rate or something like that.

Thanks beforehand!

### Additional Information

I'm currently using Minecraft 1.19 if it helps.

**Comment by Mrbysco** [comment]
I've uploaded a new version that should fix this issue
