### ISSUE TITLE
Right clicking with a chocopedia in a chocobo won't open the abilities menu[Bug]: 

### ISSUE THREAD

**Issue by LadyDaku** [Mrbysco/ChocoCraft4#23]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

1.18.2

### Mod version

1.18.2

### Java version

Java 8 update 341

### Issue Description

I expected to see a menu pop up when right-clicking a chocobo with a chocopedia to see it's abilities (and change it's name, too), but it didn't happen.

**Comment by Mrbysco** [comment]
The ability system has been removed. The mod has been reverted to the behavior before that system was implemented.
