### ISSUE TITLE
[Bug]: Breeding Issues

### ISSUE THREAD

**Issue by SartenDeLeche** [Mrbysco/ChocoCraft4#24]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

1.15.6

### Mod version

1.16.5-0.3.5

### Java version

8

### Issue Description

When i gave both of my chocobos (male and female) a lovely gysahl and they didn't breed
I though it was with that item, if not i would love if you can explain to me (or link me a guide for this mod :(

Also,  the chocopedia have GUI issues and i can' use it

**Comment by Mrbysco** [comment]
1 issue per bug report please.

Could you provide a video of the breeding not working?

**Comment by SartenDeLeche** [comment]
I gave them lovely gysahls and they don't breed. I can't give them gold gysahl also.
I
(I had to cut the video in some parts because the file was bigger than 10 MB)

https://user-images.githubusercontent.com/112553839/187737691-a30239dc-8bbc-465b-9b53-a5888d8b553d.mp4

**Comment by Mrbysco** [comment]
I've uploaded new jars to Curseforge, once they become available could you check if it fixes the breeding?

**Comment by SartenDeLeche** [comment]
Now it's working!! Thank you!!
