### ISSUE TITLE
No Bredding Purple Chocobo [Bug]: 

### ISSUE THREAD

**Issue by SartenDeLeche** [Mrbysco/ChocoCraft4#26]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

1.15.6

### Mod version

1.16.5-0.3.6

### Java version

8

### Issue Description

I read that a purple chocobo randomly lays eggs and you only have to throw them into the floor like with chicken's eggs, but mine doesn't lay eggs.
I have also tried to breed my male purple chocobo with a female of any other color with lovely and golden gysahl but it only generates yellow chicobos.
I can't try to breed him with another purple chocobo because it is impossible to find another one (I tried finding one with commands but there are none).

**Comment by Mrbysco** [comment]
The egg mechanism doesn't exist anymore

**Comment by Mrbysco** [comment]
You can't breed Purple chocobos
