### ISSUE TITLE
Chocopedie GUI overlaps/not working [Bug]: 

### ISSUE THREAD

**Issue by SartenDeLeche** [Mrbysco/ChocoCraft4#27]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

1.15.6

### Mod version

1.16.5-0.3.6

### Java version

8

### Issue Description

Screenshoot that proves the issue: (Nothing can be clicked, I can just exit using the "esc" key)
![2022-09-08_02 06 06](https://user-images.githubusercontent.com/112553839/189005935-469472e3-0e7d-4121-8638-f476317ce175.png)

**Comment by Mrbysco** [comment]
Uploaded a new version, it'll be up whenever Curseforge decides to process files again
