### ISSUE TITLE
[Bug]: Chocobo will not dive

### ISSUE THREAD

**Issue by Trawne** [Mrbysco/ChocoCraft4#3]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Forge version

36.2.8

### Mod version

0.2.1

### Java version

Java 8 Update 201

### Issue Description

Chocobo will bounce on the water continuously higher until leaving the water.

I thought it was intended until I tried to dive with a Blue chocobo. Any attempt to go underwater causes the chocobo to shoot up into the sky then bounce into the water again, regardless of if it has the dive ability or not.

Only other mod installed was JEI version 7.7.1.118

**Comment by son0fether** [comment]
I and friends are also experiencing this issue.
