### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xmbarnold** [Mrbysco/ChocoCraft4#33]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

0.207.3.6663

### Mod version

0.5.2

### Java version

Java 8 Update 341

### Issue Description

My White Chocobo will not breed with a Yellow Chocobo when I use either Loverly or Golden Gysahl Greens.

**Comment by Mrbysco** [comment]
Are you sure they're not the same gender?

**Comment by xmbarnold** [comment]
How can you tell what the gender is? I just now noticed that was a requirement.

**Comment by xmbarnold** [comment]
I can confirm that the gender was the issue. My previous Yellow Chocobo was not a name I immediately recognized from FF series. But I see this issue is user error. Sorry to bother you.

**Comment by Mrbysco** [comment]
No worries :)

**Comment by Mrbysco** [comment]
(You can notice it by the tail feathers)
