### ISSUE TITLE
[Suggestion]: Add config option for chocobo flight

### ISSUE THREAD

**Issue by taco360** [Mrbysco/ChocoCraft4#34]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [x] I would like to propose another thing

### Suggestion Description

I love this mod and want it to be included in more packs, but the golden chocobos outclass practically every form of transport once obtained (the flame chocobos are slightly better, but still overpowered in their current state). This mod has been maintained for a very long time over different creators and versions though, so I understand not wanting to make major balancing changes at this point.

So my proposal for now is to simply add a configuration option that, if enabled, will change gold and flame chocobos to jump like the other breeds rather than fly. In my opinion, they still serve their purpose as reliable and fast mounts with good storage, even without the flight.

**Comment by VeggeieDude** [comment]
I agree! Think this would be a great addition as the Gold, Pink and Red Chocobos make elytras seem a bit useless haha. That or make it much much harder to get the Gold, Pink and Red Chocobo.

Or maybe add a config to change the speed of the three flying chocobos to whatever we'd like ^^

**Comment by Mrbysco** [comment]
Once I get around to balancing out the speeds I'll see what I can do, I'm aware they're too fast

**Comment by VeggeieDude** [comment]
Awesome. Thanks!

**Comment by Mrbysco** [comment]
I've adjusted chocobo speeds slightly in 0.6.6
