### ISSUE TITLE
Bug can't breed nether chocos

### ISSUE THREAD

**Issue by SivartMcDorf** [Mrbysco/ChocoCraft4#36]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

x

### Mod version

x

### Java version

x

### Issue Description

when breeding nether chocos with either gold or loverly they only produce yellow chocos

### Additional Information

n/a

**Comment by Mrbysco** [comment]
That's intended, you've never been able to

**Comment by SivartMcDorf** [comment]
sorry, I read somewhere you could may have been someone making it up.
