### ISSUE TITLE
[Bug]: Chocobo in a boat traps the player

### ISSUE THREAD

**Issue by The-Forge-Master** [Mrbysco/ChocoCraft4#37]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.2.0

### Minecraft version

1.19.2

### Mod version

0.5.2

### Java version

OpenJDK 17.0.3

### Issue Description

Putting a Chocobo in a boat traps me on top of the Chocobo. Teleporting a short distance doesn't help, as I gets teleported right back. Teleporting a long distance lets me move again, but both the Chocobo and boat disappear when going back to the area. Upon reload, they reappear and I'm stuck once again, no matter how far away I was.

**Comment by Werewolf74** [comment]
Self for me i stuck in boat with chocobo can not sit down.

**Comment by Mrbysco** [comment]
A new version has been uploaded that fixes this issue by dismounting the chocobo from the boat if it's being ridden
