### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Andrena40** [Mrbysco/ChocoCraft4#38]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

43.2.2

### Minecraft version

1.19.2

### Mod version

0.5.3

### Java version

Java 8 update 51

### Issue Description

I have problems by trying to open the Chocopedia and also the inventory of the chocobos. I tried to check if there was some mod incompatibility that was causing that but no mods are affecting. I've seen that other people have already complained about that. Is that a real bug or am I doing something wrong? (I right clicked and everything that people say and recomend). Thank you!!

**Comment by Mrbysco** [comment]
Have you tried Shift-right-clicking the chocobo?
Also if with opening the Chocopedia you mean the stats screen, that doesn't exist anymore

**Comment by Andrena40** [comment]
Oh! I didn't know about the changes of Chocopedia. And about the Chocobo storage, I tried at first and didn't work, so I reset to default the game keys and it worked... I must have changed something and didn't realize it was that... Thank you so much for the help!
