### ISSUE TITLE
[Bug]: [Fabric 1.19.2] Can't open Chocobo's Inventory UI

### ISSUE THREAD

**Issue by kingkuys2123** [Mrbysco/ChocoCraft4#40]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Fabric version

0.14.12

### Minecraft version

1.19.2

### Mod version

0.6.0

### Java version

Java 8 Update 351

### Issue Description

Can't open Chocobo's Inventory with **Shift + R-clicking**

https://user-images.githubusercontent.com/114457180/211768361-09da182c-c3cd-4788-b7b6-9c8bd2edd839.mp4

**Comment by Mrbysco** [comment]
This will be fixed in 0.6.1 which will be up later today

**Comment by Mrbysco** [comment]
I've also updated the issue template so that there's no need to edit it after creation

**Comment by kingkuys2123** [comment]
thankss
