### ISSUE TITLE
[Bug]: Chocobo's Inventory issue

### ISSUE THREAD

**Issue by kingkuys2123** [Mrbysco/ChocoCraft4#43]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Fabric 0.14.12

### Minecraft version

1.19.2 

### Mod version

0.6.1

### Java version

Java 8 Update 351

### Issue Description

- Even without the saddle pack or saddle bags, I can still add stuff to Chocobo's inventory through shift-clicking.
- Same thing with Saddle Bags, I can still add stuff to empty slots (shaded slots) through shift-clicking.
- Saddle Bags slots are moved 1 slot to the left? Like I can see some items in some shaded slots.
- Saddle slot should only accept 1 saddle/saddle bags/saddle pack unless its intentional :)

https://user-images.githubusercontent.com/114457180/211968514-4e13aed0-b05a-41b8-a2be-7a287541f169.mp4

**Comment by Mrbysco** [comment]
I fixed it and will be uploading a new jar soon
