### ISSUE TITLE
[Suggestion]: Disabling Flight or Flight Chocobos

### ISSUE THREAD

**Issue by itsdinkd** [Mrbysco/ChocoCraft4#46]
### General Info

- [X] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

I don't believe there is any way to do this so if not, please add a config option to disable Flight or disable a list of chocobos in an array form in the json. 

**For Fabric 1.19.2 Please**
I am requesting this as I use ChocoCraft in my modpack, Another Quality Modpack 2.

**Comment by Mrbysco** [comment]
A config option has been added to disable chocobo flight all-together in 0.6.6
