### ISSUE TITLE
[Bug]: Not exactly a bug - Chocobos mod Clone on curseforge 

### ISSUE THREAD

**Issue by Mikaaah** [Mrbysco/ChocoCraft4#50]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Loader version

X

### Minecraft version

X

### Mod version

X

### Java version

X

### Issue Description

Seems like there is a chocoboclone https://www.curseforge.com/minecraft/mc-mods/dephoegons-chocobos assets are almost identical

**Comment by Mrbysco** [comment]
Not much I can do about it
