### ISSUE TITLE
[Suggestion]: Bump up the duration of the black Chocobo's night vision buff due to flashing

### ISSUE THREAD

**Issue by Revvilo** [Mrbysco/ChocoCraft4#51]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

When you're on the black Chocobo, he gives you a buff of night vision that is refreshed constantly to about 5 seconds. That duration is in the territory where the game makes the brightening effect pulsate to indicate the buff is running out, so the constant refreshing of the buff creates a strobe effect which is jarring, to say the least.

**Comment by Mrbysco** [comment]
Implemented in the latest builds for both 1.19.2 .3 and .4
