### ISSUE TITLE
[Bug]: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'chococraft'!

### ISSUE THREAD

**Issue by TheBalanceKeeper** [Mrbysco/ChocoCraft4#52]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Fabric - 0.14.19

### Minecraft version

1.19.4

### Mod version

0.6.5

### Java version

Java Version 8 Update 371

### Issue Description

I loaded chococraft through fabric api into minecaft 1.19.4 and I got the crash java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'chococraft'!  upon trying to launch minecraft.

### Additional Information

https://pastebin.com/YGB02gXp

**Comment by Mrbysco** [comment]
There's no 1.19.4 compatible version of Chococraft yet
