### ISSUE TITLE
[Bug]: Chococraft checking a property of air block crashes Minecraft

### ISSUE THREAD

**Issue by KitsuneKimmy** [Mrbysco/ChocoCraft4#53]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Fabric 0.14.19

### Minecraft version

1.19.2

### Mod version

0.6.5

### Java version

Java 8 Update 371

### Issue Description

When randomly wandering around in a single-player world on a customized modded Minecraft, the game suddenly crashes. Specifically, Minecraft freezes, then closes back to the Minecraft Launcher with an error. Based on the error logs, my understanding is that Chococraft is attempting to check an air block for its age or some other kind of tick update. This crash has happened repeatedly in single-player, and I have not yet had the chance to test it on a server. 

### Additional Information

https://pastebin.com/s6YKGKsq - Crash Log
https://pastebin.com/7CiernFS latest.log file

**Comment by Mrbysco** [comment]
Fixed in 0.6.6
