### ISSUE TITLE
[Bug]: Unable to plant Gyshal Green Seeds

### ISSUE THREAD

**Issue by Shophaune** [Mrbysco/ChocoCraft4#54]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Fabric 0.14.19

### Minecraft version

1.19.2

### Mod version

0.6.6

### Java version

Version 8 Update 331

### Issue Description

Unable to plant Gyshal Green seeds into farmland by rightclicking.

What I expected to happen:
Seeds to work like other crop seeds and be plantable.

**Comment by Mrbysco** [comment]
Will be fixed next update which should be up shortly
