### ISSUE TITLE
[Bug]: Config: "canChocobosFly" is only effective on client

### ISSUE THREAD

**Issue by Brodino96** [Mrbysco/ChocoCraft4#55]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Loader version

Fabric 0.14.21

### Minecraft version

1.19.2

### Mod version

0.6.6

### Java version

Java 18

### Issue Description

When i change the config on the server people are still able to fly with the chocobos, when i change it on my client i'm unable to fly but other people still can

**Comment by Mrbysco** [comment]
I guess I'll have to remove the config option in favor of a gamerule

**Comment by Roby1164** [comment]
It works only partially on servers. Impossible to ride a Chocobo, transferring saddle and bags, no graphic change is noticed. In addition to this, the book cannot be used, it does not open, it does not give any information ......

**Comment by Mrbysco** [comment]
> It works only partially on servers. Impossible to ride a Chocobo, transferring saddle and bags, no graphic change is noticed. In addition to this, the book cannot be used, it does not open, it does not give any information ......

Have you updated Chococraft?

**Comment by Roby1164** [comment]
Even after the latest update, where it is now possible to ride Chocobos, but the book still doesn't work, like it doesn't work, when trying to open the load of chocobo bags, this also happens to single players, moreover, it is possible only fit the saddle or the bags, not both.
In the server log I only found this string, which reports an error related to the mod:
[18:38:03] [main/ERROR]: Failed to load external book json from patchouli_books/chocopedia/book.json, skipping
java.io.FileNotFoundException: patchouli_books/chocopedia/book.json (No such file or directory)

Fabric 0.14.21
Ver 1.20.1
mod 0.9.3
