### ISSUE TITLE
[Bug]: Saddle Disappears

### ISSUE THREAD

**Issue by Mezimaru** [Mrbysco/ChocoCraft4#56]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Forge 47.1.0

### Minecraft version

1.20.1

### Mod version

chococraft-1.20.1-forge-0.9.0

### Java version

JDK 20

### Issue Description

Right-clicking a Chocobo with a saddle makes the saddle disappear, poof. Does not equip Chocobo with saddle.

Putting Saddle on Chocobo via shift-clicking into its inventory makes it disappear inside the container but does show visually on Chocobo and does enable riding.

Clicking the empty Saddle spot in its inventory will remove the saddle visually from the chocobo, it still allows you to  mount the bird but have zero movement control, such as riding a pig without a carrot.

### Additional Information

Sorry if this could have been combined with the other saddle bug report, but the versions are different and symptoms are different so wanted to post it as a new issue.

**Comment by Mrbysco** [comment]
A new build is being uploaded and should be available shortly

**Comment by Mezimaru** [comment]
Thanks so much for such a quick update. Like sincerely, that is just awesome.

I do want to just make sure you are aware that right clicking a Chocobo with a saddle still deletes the saddle with no effect on the Chocobo

**Comment by Mrbysco** [comment]
Fix is being uploaded

**Comment by Mezimaru** [comment]
> Fix is being uploaded

This would have been applied in the 0.9.2 yeah?
Still not working for me, saddle still disappears when right clicking Chocobo.
I can get my mod list or anything if need if you think it'll help, I just don't want to be a pain over an avoidable bug.

**Comment by Mrbysco** [comment]
Is it an pre-existing chocobo which was already tamed before updating? Because then it might not work

**Comment by Mezimaru** [comment]
Good idea, so I just tried spawning in a new goldy and attempted to right-click with the three different saddles. It works in creative as far as it applying the saddle to the chocobo, but in survival it still just deletes them with no effect. I did just update the server to the new 47.1.19 forge as well if that might affect something.

**Comment by Mrbysco** [comment]
It's working for me just fine (I use 47.1.3 in dev)

**Comment by Mezimaru** [comment]
So helping to troubleshoot this further, I made a new curseforge profile using 47.1.3 and only Chococraft + Architectury as the mods. Included video below.

https://youtu.be/4AGGWyB7_u4

**Comment by Mrbysco** [comment]
Are you sure you're up to date? I made a new instance with Chococraft 0.9.4 and Architectury 9.1.10 with Forge 47.1.3 and was unable to reproduce your issue

**Comment by Mezimaru** [comment]
Here's another video for reference. I'm not sure what the difference would be, but I'm willing to troubleshoot whatever.

(Video quality is crap until HD version finishes uploading)
https://youtu.be/suZPsQctzlw

**Comment by Mezimaru** [comment]
I think I found the problem here,
It works fine if holding 2+ saddles in a stack, however if holding only a single saddle in your hand when right-clicking, it looks like the saddle is being removed from player before being placed on the chocobo.

**Comment by Mrbysco** [comment]
A possible bugfix has been implemented and is being backported all the way to 1.19.2

**Comment by Mezimaru** [comment]
Looks like its working for me now, the saddle is now being applied to the chocobo on right click.
Appreciate it!
Side Note:  One last QoL thought on this matter, the player seems to apply saddle and instantly mount chocobo at the same time.
