### ISSUE TITLE
[Suggestion]: Italian translation

### ISSUE THREAD

**Issue by Roby1164** [Mrbysco/ChocoCraft4#57]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

I attach file with Italian translation.

[it_it.zip](https://github.com/Mrbysco/ChocoCraft4/files/12063396/it_it.zip)

**Comment by Mrbysco** [comment]
Will be included in future builds
