### ISSUE TITLE
[Bug]: Nothing from pack spawns and recipes don't show in JEI.

### ISSUE THREAD

**Issue by The-Druid-Box** [Mrbysco/ChocoCraft4#62]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the mod

### Loader version

43.2.8

### Minecraft version

1.19.2

### Mod version

0.6.12

### Java version

17.0.3 64bit

### Issue Description

It seems all recipes and spawns are broken.  The items show in JEI, but clicking them doesn't present a recipe or any further information.

**Comment by Mrbysco** [comment]
New jars are being uploaded that should fix the problem
