### ISSUE TITLE
[Bug]: A texture bug? 

### ISSUE THREAD

**Issue by SoyJetixXD** [Mrbysco/ChocoCraft4#67]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Forge 36.2.39

### Minecraft version

1.16.5

### Mod version

0.3.9

### Java version

Java 8 381

### Issue Description

**Hello!**
The small bug affects all types of Chocobo.
Well this will be somewhat complicated to explain, but I will try.
Or it would be better if you see it.
The video is very heavy and you cannot see it directly here, so I will send you a download link.
https://www.mediafire.com/file/xhxi5hcnx2ung8p/BUG.mp4/file
Thank you very much for reading and I hope you see it in full.

### Additional Information

.

**Comment by Mrbysco** [comment]
Could you upload it to a website like youtube and make it unlisted? I don't really trust downloading a random file

**Comment by SoyJetixXD** [comment]
Of course, my fault.
https://youtu.be/8fCiCwjBzCc

**Comment by Mrbysco** [comment]
1.16.5 is no longer actively developed so unless a major issue is found like a crash it likely won't be fixed soon

**Comment by SoyJetixXD** [comment]
I understand, it's a shame.

**Comment by AzraelTheOnly** [comment]
> I understand, it's a shame.

I was just going to post this error, although it is a minor one, it is somewhat unpleasant.
It's sad to know that they are forgetting this wonderful version :/
I hope one day they fix it.
postscript: the video explains the bug very well, I congratulate you :)
