### ISSUE TITLE
[Suggestion]: Gysahl Green patch rarity config

### ISSUE THREAD

**Issue by Keyedrin** [Mrbysco/ChocoCraft4#68]
### General Info

- [ ] I would like to propose new content
- [x] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

I would like to propose a change to the config that will allow for adjustment of the wild Gysahl patch rarity. They are quite common and I would like to reduce the occurrence of wild patches.

**Comment by Mrbysco** [comment]
In 1.19+ this can't be done on Forge without hardcoding

**Comment by Mrbysco** [comment]
You should be able to change it by creating a datapack
