### ISSUE TITLE
[Bug]:  

### ISSUE THREAD

**Issue by phoenix6002** [Mrbysco/ChocoCraft4#70]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

forge-36.2.41

### Minecraft version

1.16.5

### Mod version

0.3.9

### Java version

Java 8 update 401

### Issue Description

when i right clik with the chocopedia to a chocobo nothing happens

### Additional Information

![2024-02-13_19 03 54](https://github.com/Mrbysco/ChocoCraft4/assets/58641516/36bedf1e-affb-4eaf-aa07-a7702f7c7dd6)

**Comment by Mrbysco** [comment]
This is not ChocoCraft 3, there's no stats screen. ChocoCraft 4 tries to stay close to the original behavior where you have to breed different colors.
