### ISSUE TITLE
[Suggestion]: 1.20.4 update

### ISSUE THREAD

**Issue by vico93** [Mrbysco/ChocoCraft4#71]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

More a question than a suggestion, but are there plans to update this mod to 1.20.4? I'm really interested in try it when updated.

**Comment by Mrbysco** [comment]
It's planned

**Comment by Mrbysco** [comment]
Done

**Comment by Mrbysco** [comment]
(It'll be up shortly)

**Comment by vico93** [comment]
Thanks a lot for this!
