### ISSUE TITLE
[Bug]: Instant disconnect when joining world. (Error: Index 4 out of bounds for length 3.)

### ISSUE THREAD

**Issue by Gbergz** [Mrbysco/ChocoCraft4#73]
### General Info

- [X] I am running a modpack | This: [v0.40.0](https://legacy.curseforge.com/minecraft/modpacks/tnp-limitless-7/files/5133904)
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player, when encountered.
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Forge 47.2.17

### Minecraft version

1.20.1

### Mod version

0.9.10 | https://legacy.curseforge.com/minecraft/mc-mods/chococraft/files/4656792

### Java version

Java 17 (v17.0.10)

### Issue Description

Playing normal for awhile then later disconnected, and when later rejoining the multiplayer server the user gets disconnected with the following message: `(java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 3)`

This is consistent until the mod is removed, reproduced while exploring world.
Had to remove the mod from my modpack for the time being until this can maybe be fixed as it was quite common.

Any ideas? Crash report & logs below.
**-** Gbergz

### Additional Information

Crash-report: https://gist.githubusercontent.com/Gbergz/9d56524ce85a9b6136beebd34010eee1/raw/230a41886a5509520c442f25dbc5a77029a80a1f/gistfile1.txt

Logs: https://gist.githubusercontent.com/Gbergz/7ee3d8a271911d54561460f94d1be939/raw/24350d69feb3a05ce92e901952785d836e74ac9d/gistfile1.txt

**Comment by Mrbysco** [comment]
A new version is being uploaded `0.9.11` which will probably fix this. 
I'm unable to reproduce it but I noticed that the implementation I was using could be replaced by a vanilla method.

**Comment by Gbergz** [comment]
Awesome, thanks for the swift fix!

**Comment by Mrbysco** [comment]
Did it fix your problem?

**Comment by Gbergz** [comment]
Haven't had a chance to test as it wasn't reproducable every time. But I'll update here when I can confirm fully.
