### ISSUE TITLE
[Bug]: bugged armor textures

### ISSUE THREAD

**Issue by Sareth23** [Mrbysco/ChocoCraft4#77]
### General Info

- [ ] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

forge 1.20.1

### Minecraft version

1.20.1

### Mod version

0.9.11

### Java version

java 8 51

### Issue Description

I have been searching for many hours to find out what the problem is with the textures and I can't find it, please I need help
![Captura de pantalla 2024-05-28 183617](https://github.com/Mrbysco/ChocoCraft4/assets/164009527/feeca256-1834-4946-9ef4-687b15d0d88d)
![Captura de pantalla 2024-05-28 183757](https://github.com/Mrbysco/ChocoCraft4/assets/164009527/f334e009-bad2-4cc8-8b10-f401791d987b)

**Comment by Mrbysco** [comment]
Log file?

**Comment by Mrbysco** [comment]
What other mods are installed?

**Comment by Sareth23** [comment]
> ¿Qué otras modificaciones están instaladas?


I only have the chococraft mod

**Comment by Mrbysco** [comment]
Impossible, vanilla has no shaders
