### ISSUE TITLE
[Bug]: Server crash on startup

### ISSUE THREAD

**Issue by NielsPilgaard** [Mrbysco/ChocoCraft4#81]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

Neoforge 21.0.42

### Minecraft version

1.21.0

### Mod version

chococraft-1.21-neoforge-0.11.2

### Java version

Java 21

### Issue Description

The server crashes on startup

### Additional Information

https://gist.github.com/NielsPilgaard/cb3fec43f37d7fed86c2bf1c40fac356

**Comment by Mrbysco** [comment]
Will fix once I have access to a pc again

**Comment by NielsPilgaard** [comment]
Sounds good 👍
