### ISSUE TITLE
[Suggestion]: Backport 0.11.6 to 1.20.1

### ISSUE THREAD

**Issue by nx5314** [Mrbysco/ChocoCraft4#88]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Most larger modpacks are still on 1.20.1 for the time being, could 0.11.6 or the inventory fixes be backported to a 1.20.1 build?

**Comment by Mrbysco** [comment]
Done, a version will be up shortly
