### ISSUE TITLE
[Bug]: Crash: Rendering entity in world when opening Chocobo's inventory

### ISSUE THREAD

**Issue by rsmalec** [Mrbysco/ChocoCraft4#9]
### General Info

- [ ] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

39.0.75

### Mod version

1.18.1-0.2.3

### Java version

17.0.1

### Issue Description

I created saddle bags and equipped them on a yellow chocobo.
I filled the chocobo's inventory with various items with another chocobo saddle and gyshal greens inside.  No issues.
(see entity data below)

When I came back to my chocobo later and tried to re-open its inventory, I crash every time

[crash-2022-02-18_22.00.08-client.txt](https://github.com/Mrbysco/ChocoCraft4/files/8101409/crash-2022-02-18_22.00.08-client.txt)
.

**Comment by rsmalec** [comment]
![2022-02-18_22 13 46](https://user-images.githubusercontent.com/2677673/154785711-11f980b9-f554-4c5b-bd76-5c6801c2f396.png)

I took a screenshot of entity data so you can see what is in his inventory.

**Comment by Mrbysco** [comment]
Could you provide the latest log of that time?

**Comment by Mrbysco** [comment]
I've backported my overhaul. Please check if the issue persists and if it does I'll re-open the issue
