### ISSUE TITLE
[Bug]: Choco pens not healing Chocobos

### ISSUE THREAD

**Issue by MuteTiefling** [Mrbysco/ChocoCraft4#90]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Loader version

neoforge-21.0.167

### Minecraft version

1.21

### Mod version

chococraft-1.21-neoforge-0.11.5

### Java version

21.0.3

### Issue Description

Chocobo pens do not appear to heal chocobos. 

### Additional Information

https://github.com/EnigmaticaModpacks/Enigmatica10/issues/73

**Comment by Mrbysco** [comment]
Works for me with a water filled cauldron. Might've been fixed by a recent commit. Will upload new build

**Comment by MuteTiefling** [comment]
Awesome thanks. Was the described pen in the correct dimensions?

**Comment by Mrbysco** [comment]
No clue 🤷

**Comment by MuteTiefling** [comment]
Apologies for taking so long to get back around to this. 

Here's my test pen. 5x5 of straw with a filled cauldron in the middle. 

![image](https://github.com/user-attachments/assets/d4d3c444-5cd3-475c-a27c-0b48b7c4ada3)


I've hit these guys with a splash harm potion so they're all at 38 health. So far, it's been about 10 minutes and none of them have healed.

**Comment by Mrbysco** [comment]
Are they all tamed or not?

**Comment by MuteTiefling** [comment]
They are not, wasn't aware that was a requirement

**Comment by Mrbysco** [comment]
The pen healing is a goal that is applied to the AI of the Chocobo when tamed last I checked

**Comment by MuteTiefling** [comment]
ok, been a good 20 minutes and this guy is still fully hurt 
![image](https://github.com/user-attachments/assets/2b52de8c-a2ef-45e9-9402-66c8a1d4b589)

**Comment by MuteTiefling** [comment]
ok, it's just very slow. this guy finally healed :D
