### ISSUE TITLE
[Suggestion]: Rebalance Chocodisguise Armor

### ISSUE THREAD

**Issue by JohnGoten** [Mrbysco/ChocoCraft4#91]
### General Info

- [ ] I would like to propose new content
- [X] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

Due to the low cost and effort involved to get ahold of a full set of Chocodisguise Armor I would kindly suggest for it to be nerfed to an equivalent of leather armor.
It is very questionable for there to be an armor set mathematically outperforming iron and nearing diamond level other than the "missing" armor toughness. And whilst I am full aware of the already quite non-existent balance in the vanilla game, amplifying this issue harms balance even further.

Example:
Helmet > 1 Armor, 0.5 Armor Toughness
Body > 3 Armor, 0.5 Armor Toughness
Legs > 2 Armor, 0.5 Armor Toughness
Boots > 1 Armor, 0.5 Armor Toughness
or alternatively in exchange for the armor toughness, grant a full set bonus which remove all powder snow freeze damage.

I am genuinely unable to wrap my head around the poor game design that went into deciding for some basic common mob drops to fully kit out the player with armor which they may never even have to swap again.

**Comment by JohnGoten** [comment]
A month has passed and whilst this may have been a mere suggestion to improve this previously - referring to the original - rather promising mod, I have come the conclusion it is of no interest for the responsible individual(s) to give a care about the countless of projects they somehow keep updated at all times

Deeply disappointed by mass-produced slop that players support with their downloads. Do it like reasonable people, stick to a handful or less and refine your work
Looks like I will have to put this one on my blacklist alongside Serilum and Lupin

**Comment by CammiePone** [comment]
[r/iamverysmart](https://www.reddit.com/r/iamverysmart/)
